version: '3.4'
services:
  postgres:
    restart: always
    container_name: email-db
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  postgres_data: