service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    PG_HOST: localhost
    PG_PORT: 5432
    PG_USER: admin
    PG_PASSWORD: admin
    PG_DATABASE: mydb

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'